### PR TITLE
Disable start/pause button until the user is 2

### PR DESCRIPTION
**Pull request by kachick**
disabled

### CODE REVIEW

**Comment by pankona** [comment]
Seems good but there're diffs in yarn.lock 🤔 
Could you please try `yarn upgrade`?

**Comment by kachick** [comment]
Sure. I did in https://github.com/pankona/mobu/pull/34/commits/254dff3ea010eace0300e4ecba2e9d23f60b10aa

**Comment by pankona** [comment]
Great!! 😋

**Comment by kachick** [comment]
Thank you!

**Pull request merged**
